Create Fresh.js
RoyaliTEA-News/radios pull request #17
Opened 2021-11-14 22:01 UTC by ItzJonax

2021-11-14 22:02 UTC, callumok2004 requested changes
Fresh isnt even open.. close this

2021-11-14 22:02 UTC, callumok2004 commented
the site is up as a joke

2021-11-14 22:04 UTC, ItzJonax commented
> Fresh isnt even open.. close this

what? yes it is i literally set up everything for them

2021-11-14 23:10 UTC, callumok2004 requested changes

2021-11-14 23:10 UTC, callumok2004 commented on services/Fresh.js
> +    "aliases": ["fresh", "freshradio", "fr"],
remove the name as an alias

2021-11-14 23:10 UTC, callumok2004 commented on services/Fresh.js
> +    "id": "13d4a520-3329-4afb-9292-c9356c67b7cf",
i hope this is not the same as any other!

2021-11-15 08:02 UTC, PiggyPlex commented on services/Fresh.js
> +    "id": "13d4a520-3329-4afb-9292-c9356c67b7cf",
fr

2021-11-15 08:04 UTC, PiggyPlex approved these changes
ofc i approve of my own changes !!

2021-11-15 08:04 UTC, merged